<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            ['initialism' => 'AA', 'name' => 'Açúcar e Álcool'],
            ['initialism' => 'ADM', 'name' => 'Administração'],
            ['initialism' => 'ABD', 'name' => 'Administrador de Banco de Dados'],
            ['initialism' => 'AGVI', 'name' => 'Agenciamento de Viagem'],
            ['initialism' => 'AGMA', 'name' => 'Agenciamento Marítimo'],
            ['initialism' => 'ACS', 'name' => 'Agente Comunitário de Saúde'],
            ['initialism' => 'AGRI', 'name' => 'Agricultura'],
            ['initialism' => 'AGRM', 'name' => 'Agrimensura'],
            ['initialism' => 'AGEC', 'name' => 'Agroecologia'],
            ['initialism' => 'AGIN', 'name' => 'Agroindústria'],
            ['initialism' => 'AGNE', 'name' => 'Agronegócio'],
            ['initialism' => 'AGRP', 'name' => 'Agropecuária'],
            ['initialism' => 'ALIM', 'name' => 'Alimentos'],
            [
                'initialism' => 'ADQS',
                'name' => 'Análise de Dados para Questões Sociais',
            ],
            ['initialism' => 'ARQV', 'name' => 'Arquivo'],
            ['initialism' => 'AP', 'name' => 'Assessoria Parlamentar'],
            ['initialism' => 'ARH', 'name' => 'Assistente de Recursos Humanos'],
            ['initialism' => 'AI', 'name' => 'Automação Industrial'],
            ['initialism' => 'AUPR', 'name' => 'Automação Predial'],
            [
                'initialism' => 'AAFMC',
                'name' =>
                    'Auxiliar Administrativo, Auxiliar de Finanças e Auxiliar de Marketing e Comercial',
            ],
            ['initialism' => 'BIBL', 'name' => 'Biblioteconomia'],
            ['initialism' => 'BPRO', 'name' => 'Bioprocessos'],
            ['initialism' => 'BIOT', 'name' => 'Biotecnologia'],
            ['initialism' => 'CAFE', 'name' => 'Cafeicultura'],
            ['initialism' => 'CT', 'name' => 'Cálculos Trabalhistas'],
            ['initialism' => 'CANT', 'name' => 'Canto'],
            ['initialism' => 'CP', 'name' => 'Celulose e Papel'],
            [
                'initialism' => 'CCIC',
                'name' => 'Centro Cirúrgico e Instrumentação Cirúrgica',
            ],
            ['initialism' => 'CD', 'name' => 'Ciência de Dados'],
            [
                'initialism' => 'CNT',
                'name' => 'Ensino Médio com ênfase em Ciências da Natureza e suas Tecnologias',
            ],
            [
                'initialism' => 'CHS',
                'name' => 'Ensino Médio com ênfase em Ciências Humanas e Sociais Aplicadas',
            ],
            ['initialism' => 'COM', 'name' => 'Comércio'],
            ['initialism' => 'COMEX', 'name' => 'Comércio Exterior'],
            ['initialism' => 'CA', 'name' => 'Composição e Arranjo'],
            ['initialism' => 'COND', 'name' => 'Condomínio'],
            ['initialism' => 'CONT', 'name' => 'Contabilidade'],
            ['initialism' => 'CI', 'name' => 'Cuidados de Idosos'],
            ['initialism' => 'CURT', 'name' => 'Curtimento'],
            ['initialism' => 'DANC', 'name' => 'Dança'],
            ['initialism' => 'DSAL', 'name' => 'Dança de Salão'],
            ['initialism' => 'DD', 'name' => 'Danças a Dois'],
            ['initialism' => 'DC', 'name' => 'Defesa Civil'],
            ['initialism' => 'DCC', 'name' => 'Desenho de Construção Civil'],
            ['initialism' => 'DCOM', 'name' => 'Desenvolvimento Comunitário'],
            [
                'initialism' => 'DAS',
                'name' => 'Desenvolvimento de Aplicativos para Smartphones',
            ],
            [
                'initialism' => 'DNPA',
                'name' => 'Desenvolvimento de novos Produtos para a Área da Indústria Alimentícia',
            ],
            ['initialism' => 'DS', 'name' => 'Desenvolvimento de Sistemas'],
            ['initialism' => 'DI', 'name' => 'Design de Interiores'],
            ['initialism' => 'DM', 'name' => 'Design de Moda'],
            ['initialism' => 'DMOV', 'name' => 'Design de Móveis'],
            ['initialism' => 'DG', 'name' => 'Design Gráfico'],
            ['initialism' => 'EDIF', 'name' => 'Edificações'],
            ['initialism' => 'ELED', 'name' => 'Eletroeletrônica'],
            ['initialism' => 'EMEC', 'name' => 'Eletromecânica'],
            ['initialism' => 'ELET', 'name' => 'Eletrônica'],
            ['initialism' => 'ELTC', 'name' => 'Eletrotécnica'],
            ['initialism' => 'ENF', 'name' => 'Enfermagem'],
            ['initialism' => 'ENFT', 'name' => 'Enfermagem do Trabalho'],
            ['initialism' => 'EAI', 'name' => 'Enfermagem na Assistência ao Idoso'],
            ['initialism' => 'ENOG', 'name' => 'Enogastronomia'],
            ['initialism' => 'EB', 'name' => 'Equipamentos Biomédicos'],
            ['initialism' => 'EVEN', 'name' => 'Eventos'],
            ['initialism' => 'FIM', 'name' => 'Fabricação de Instrumentos Musicais'],
            ['initialism' => 'FM', 'name' => 'Fabricação Mecânica'],
            ['initialism' => 'FARM', 'name' => 'Farmácia'],
            ['initialism' => 'FIN', 'name' => 'Finanças'],
            ['initialism' => 'FLOR', 'name' => 'Florestas'],
            ['initialism' => 'GAST', 'name' => 'Gastronomia'],
            ['initialism' => 'GB', 'name' => 'Gastronomia Brasileira'],
            ['initialism' => 'GH', 'name' => 'Gastronomia Hospitalar'],
            ['initialism' => 'GI', 'name' => 'Gastronomia Internacional'],
            ['initialism' => 'GEOP', 'name' => 'Geoprocessamento'],
            ['initialism' => 'GA', 'name' => 'Gestão Ambiental'],
            ['initialism' => 'GE', 'name' => 'Gestão de Energia'],
            ['initialism' => 'GP', 'name' => 'Gestão de Projetos – EaD'],
            [
                'initialism' => 'GUAN',
                'name' => 'Gestão de Unidades de Alimentação e Nutrição',
            ],
            ['initialism' => 'GT', 'name' => 'Guia de Turismo'],
            ['initialism' => 'GTI', 'name' => 'Guia de Turismo Internacional'],
            ['initialism' => 'HIDR', 'name' => 'Hidrologia'],
            ['initialism' => 'HO', 'name' => 'Higiene Ocupacional'],
            ['initialism' => 'HOSP', 'name' => 'Hospedagem'],
            ['initialism' => 'INFO', 'name' => 'Informática'],
            ['initialism' => 'IPI', 'name' => 'Informática para Internet'],
            ['initialism' => 'IM', 'name' => 'Instrumento Musical'],
            ['initialism' => 'JAVAWR', 'name' => 'JAVA-WR'],
            ['initialism' => 'LAZE', 'name' => 'Lazer'],
            [
                'initialism' => 'LGG',
                'name' => 'Ensino Médio com ênfase em Linguagens e suas Tecnologias',
            ],
            ['initialism' => 'LOG', 'name' => 'Logística'],
            ['initialism' => 'LR', 'name' => 'Logística Reversa'],
            ['initialism' => 'MAUT', 'name' => 'Manutenção Automotiva'],
            ['initialism' => 'MMP', 'name' => 'Manutenção de Máquinas Pesadas'],
            ['initialism' => 'MSI', 'name' => 'Manutenção e Suporte em Informática'],
            ['initialism' => 'MKT', 'name' => 'Marketing'],
            [
                'initialism' => 'MAT',
                'name' => 'Ensino Médio com ênfase em Matemática e suas Tecnologias',
            ],
            ['initialism' => 'MEC', 'name' => 'Mecânica'],
            ['initialism' => 'MECA', 'name' => 'Mecanização Agrícola'],
            ['initialism' => 'MTR', 'name' => 'Mecatrônica'],
            ['initialism' => 'MA', 'name' => 'Meio Ambiente'],
            ['initialism' => 'MET', 'name' => 'Metalurgia'],
            ['initialism' => 'MINE', 'name' => 'Mineração'],
            ['initialism' => 'MV', 'name' => 'Modelagem do Vestuário'],
            ['initialism' => 'MOVE', 'name' => 'Móveis'],
            ['initialism' => 'MULT', 'name' => 'Multimídia'],
            ['initialism' => 'MUSE', 'name' => 'Museologia'],
            ['initialism' => 'ND', 'name' => 'Nutrição e Dietética'],
            ['initialism' => 'ONCO', 'name' => 'Oncologia'],
            ['initialism' => 'OEC', 'name' => 'Organização de Eventos Corporativos'],
            ['initialism' => 'OE', 'name' => 'Organização Esportiva'],
            ['initialism' => 'OP', 'name' => 'Órteses e Próteses'],
            ['initialism' => 'PAIS', 'name' => 'Paisagismo'],
            ['initialism' => 'PC', 'name' => 'Panificação e Confeitaria'],
            ['initialism' => 'PORT', 'name' => 'Portos'],
            ['initialism' => 'PF', 'name' => 'Processos Fotográficos'],
            ['initialism' => 'PRCU', 'name' => 'Produção Cultural'],
            ['initialism' => 'PAV', 'name' => 'Produção de Áudio e Vídeo'],
            ['initialism' => 'PCA', 'name' => 'Produção de Cana de Açúcar'],
            ['initialism' => 'PJD', 'name' => 'Programação de Jogos Digitais'],
            ['initialism' => 'PD', 'name' => 'Prótese Dentária'],
            ['initialism' => 'PFEC', 'name' => 'Prótese fixa com ênfase em cerâmica'],
            ['initialism' => 'PO', 'name' => 'Prótese Ortodôntica'],
            ['initialism' => 'PSI', 'name' => 'Prótese Sobre Implantes'],
            ['initialism' => 'PUBL', 'name' => 'Publicidade'],
            ['initialism' => 'QUAL', 'name' => 'Qualidade'],
            ['initialism' => 'QUIM', 'name' => 'Química'],
            ['initialism' => 'RDCM', 'name' => 'Rádiocomunicação'],
            ['initialism' => 'RH', 'name' => 'Recursos Humanos'],
            ['initialism' => 'RC', 'name' => 'Redes de Computadores'],
            ['initialism' => 'REGE', 'name' => 'Regência'],
            ['initialism' => 'SANE', 'name' => 'Saneamento'],
            ['initialism' => 'SB', 'name' => 'Saúde Bucal'],
            ['initialism' => 'SDTR', 'name' => 'Saúde do Trabalhador'],
            ['initialism' => 'SEC', 'name' => 'Secretariado'],
            [
                'initialism' => 'SACQ',
                'name' =>
                    'Segurança do Alimento – Ênfase em Controle de Qualidade em Unidade de Alimentação e Nutrição',
            ],
            ['initialism' => 'ST', 'name' => 'Segurança do Trabalho'],
            [
                'initialism' => 'STCC',
                'name' => 'Segurança do Trabalho na Construção Civil',
            ],
            ['initialism' => 'SEGU', 'name' => 'Seguros'],
            ['initialism' => 'SRB', 'name' => 'Serviços de Restaurante e Bar'],
            ['initialism' => 'SJ', 'name' => 'Serviços Jurídicos'],
            ['initialism' => 'SP', 'name' => 'Serviços Públicos'],
            ['initialism' => 'SF', 'name' => 'Sistema Fotovoltaico'],
            ['initialism' => 'SER', 'name' => 'Sistemas de Energia Renovável'],
            ['initialism' => 'SOLD', 'name' => 'Soldagem'],
            [
                'initialism' => 'SMEI',
                'name' => 'Supervisão de Manutenção Elétrica Industrial',
            ],
            ['initialism' => 'TEAT', 'name' => 'Teatro'],
            ['initialism' => 'LEGI', 'name' => 'Legislativo'],
            ['initialism' => 'TELE', 'name' => 'Telecomunicações'],
            ['initialism' => 'TI', 'name' => 'Transações Imobiliárias'],
            ['initialism' => 'TM', 'name' => 'Transporte Metroferroviário'],
            ['initialism' => 'TR', 'name' => 'Transporte Rodoviário'],
            ['initialism' => 'TE', 'name' => 'Turismo de Experiência'],
            ['initialism' => 'TURR', 'name' => 'Turismo Receptivo'],
            [
                'initialism' => 'APH',
                'name' => 'Urgência e Emergência – APH (Atendimento Pré-Hospitalar)',
            ],
            ['initialism' => 'VEST', 'name' => 'Vestuário'],
            ['initialism' => 'VET', 'name' => 'Veterinária'],
            ['initialism' => 'VIDR', 'name' => 'Vidro'],
            ['initialism' => 'VE', 'name' => 'Viticultura e Enologia'],
            ['initialism' => 'ZOOT', 'name' => 'Zootecnia'],
        ];

        foreach (array_chunk($courses, 100) as $chunk) {
            DB::table('courses')->insert($chunk);
        }
    }
}
