<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            ['initialism' => 'AA', 'name' => 'Açúcar e Álcool', 'icon_id' => 16],
            ['initialism' => 'ADM', 'name' => 'Administração', 'icon_id' => 6],
            ['initialism' => 'ABD', 'name' => 'Administrador de Banco de Dados', 'icon_id' => 1],
            ['initialism' => 'AGVI', 'name' => 'Agenciamento de Viagem', 'icon_id' => 24],
            ['initialism' => 'AGMA', 'name' => 'Agenciamento Marítimo', 'icon_id' => 9],
            ['initialism' => 'ACS', 'name' => 'Agente Comunitário de Saúde', 'icon_id' => 22],
            ['initialism' => 'AGRI', 'name' => 'Agricultura', 'icon_id' => 16],
            ['initialism' => 'AGRM', 'name' => 'Agrimensura', 'icon_id' => 18],
            ['initialism' => 'AGEC', 'name' => 'Agroecologia', 'icon_id' => 16],
            ['initialism' => 'AGIN', 'name' => 'Agroindústria', 'icon_id' => 16],
            ['initialism' => 'AGNE', 'name' => 'Agronegócio', 'icon_id' => 16],
            ['initialism' => 'AGRP', 'name' => 'Agropecuária', 'icon_id' => 16],
            ['initialism' => 'ALIM', 'name' => 'Alimentos', 'icon_id' => 15],
            [
                'initialism' => 'ADQS',
                'name' => 'Análise de Dados para Questões Sociais',
                'icon_id' => 1,
            ],
            ['initialism' => 'ARQV', 'name' => 'Arquivo', 'icon_id' => 6],
            ['initialism' => 'AP', 'name' => 'Assessoria Parlamentar', 'icon_id' => 6],
            ['initialism' => 'ARH', 'name' => 'Assistente de Recursos Humanos', 'icon_id' => 7],
            ['initialism' => 'AI', 'name' => 'Automação Industrial', 'icon_id' => 13],
            ['initialism' => 'AUPR', 'name' => 'Automação Predial', 'icon_id' => 13],
            [
                'initialism' => 'AAFMC',
                'name' =>
                    'Auxiliar Administrativo, Auxiliar de Finanças e Auxiliar de Marketing e Comercial',
                'icon_id' => 6,
            ],
            ['initialism' => 'BIBL', 'name' => 'Biblioteconomia', 'icon_id' => 6],
            ['initialism' => 'BPRO', 'name' => 'Bioprocessos', 'icon_id' => 14],
            ['initialism' => 'BIOT', 'name' => 'Biotecnologia', 'icon_id' => 14],
            ['initialism' => 'CAFE', 'name' => 'Cafeicultura', 'icon_id' => 16],
            ['initialism' => 'CT', 'name' => 'Cálculos Trabalhistas', 'icon_id' => 10],
            ['initialism' => 'CANT', 'name' => 'Canto', 'icon_id' => 21],
            ['initialism' => 'CP', 'name' => 'Celulose e Papel', 'icon_id' => 14],
            [
                'initialism' => 'CCIC',
                'name' => 'Centro Cirúrgico e Instrumentação Cirúrgica',
                'icon_id' => 22,
            ],
            ['initialism' => 'CD', 'name' => 'Ciência de Dados', 'icon_id' => 3],
            [
                'initialism' => 'CNT',
                'name' => 'Ensino Médio com ênfase em Ciências da Natureza e suas Tecnologias',
                'icon_id' => 0,
            ],
            [
                'initialism' => 'CHS',
                'name' => 'Ensino Médio com ênfase em Ciências Humanas e Sociais Aplicadas',
                'icon_id' => 0,
            ],
            ['initialism' => 'COM', 'name' => 'Comércio', 'icon_id' => 6],
            ['initialism' => 'COMEX', 'name' => 'Comércio Exterior', 'icon_id' => 9],
            ['initialism' => 'CA', 'name' => 'Composição e Arranjo', 'icon_id' => 21],
            ['initialism' => 'COND', 'name' => 'Condomínio', 'icon_id' => 6],
            ['initialism' => 'CONT', 'name' => 'Contabilidade', 'icon_id' => 10],
            ['initialism' => 'CI', 'name' => 'Cuidados de Idosos', 'icon_id' => 22],
            ['initialism' => 'CURT', 'name' => 'Curtimento', 'icon_id' => 14],
            ['initialism' => 'DANC', 'name' => 'Dança', 'icon_id' => 21],
            ['initialism' => 'DSAL', 'name' => 'Dança de Salão', 'icon_id' => 21],
            ['initialism' => 'DD', 'name' => 'Danças a Dois', 'icon_id' => 21],
            ['initialism' => 'DC', 'name' => 'Defesa Civil', 'icon_id' => 23],
            ['initialism' => 'DCC', 'name' => 'Desenho de Construção Civil', 'icon_id' => 17],
            ['initialism' => 'DCOM', 'name' => 'Desenvolvimento Comunitário', 'icon_id' => 6],
            [
                'initialism' => 'DAS',
                'name' => 'Desenvolvimento de Aplicativos para Smartphones',
                'icon_id' => 1,
            ],
            [
                'initialism' => 'DNPA',
                'name' => 'Desenvolvimento de novos Produtos para a Área da Indústria Alimentícia',
                'icon_id' => 15,
            ],
            ['initialism' => 'DS', 'name' => 'Desenvolvimento de Sistemas', 'icon_id' => 1],
            ['initialism' => 'DI', 'name' => 'Design de Interiores', 'icon_id' => 19],
            ['initialism' => 'DM', 'name' => 'Design de Moda', 'icon_id' => 19],
            ['initialism' => 'DMOV', 'name' => 'Design de Móveis', 'icon_id' => 19],
            ['initialism' => 'DG', 'name' => 'Design Gráfico', 'icon_id' => 19],
            ['initialism' => 'EDIF', 'name' => 'Edificações', 'icon_id' => 17],
            ['initialism' => 'ELED', 'name' => 'Eletroeletrônica', 'icon_id' => 12],
            ['initialism' => 'EMEC', 'name' => 'Eletromecânica', 'icon_id' => 11],
            ['initialism' => 'ELET', 'name' => 'Eletrônica', 'icon_id' => 12],
            ['initialism' => 'ELTC', 'name' => 'Eletrotécnica', 'icon_id' => 12],
            ['initialism' => 'ENF', 'name' => 'Enfermagem', 'icon_id' => 22],
            ['initialism' => 'ENFT', 'name' => 'Enfermagem do Trabalho', 'icon_id' => 22],
            [
                'initialism' => 'EAI',
                'name' => 'Enfermagem na Assistência ao Idoso',
                'icon_id' => 22,
            ],
            ['initialism' => 'ENOG', 'name' => 'Enogastronomia', 'icon_id' => 15],
            ['initialism' => 'EB', 'name' => 'Equipamentos Biomédicos', 'icon_id' => 22],
            ['initialism' => 'EVEN', 'name' => 'Eventos', 'icon_id' => 21],
            [
                'initialism' => 'FIM',
                'name' => 'Fabricação de Instrumentos Musicais',
                'icon_id' => 11,
            ],
            ['initialism' => 'FM', 'name' => 'Fabricação Mecânica', 'icon_id' => 11],
            ['initialism' => 'FARM', 'name' => 'Farmácia', 'icon_id' => 22],
            ['initialism' => 'FIN', 'name' => 'Finanças', 'icon_id' => 10],
            ['initialism' => 'FLOR', 'name' => 'Florestas', 'icon_id' => 16],
            ['initialism' => 'GAST', 'name' => 'Gastronomia', 'icon_id' => 15],
            ['initialism' => 'GB', 'name' => 'Gastronomia Brasileira', 'icon_id' => 15],
            ['initialism' => 'GH', 'name' => 'Gastronomia Hospitalar', 'icon_id' => 15],
            ['initialism' => 'GI', 'name' => 'Gastronomia Internacional', 'icon_id' => 15],
            ['initialism' => 'GEOP', 'name' => 'Geoprocessamento', 'icon_id' => 18],
            ['initialism' => 'GA', 'name' => 'Gestão Ambiental', 'icon_id' => 16],
            ['initialism' => 'GE', 'name' => 'Gestão de Energia', 'icon_id' => 4],
            ['initialism' => 'GP', 'name' => 'Gestão de Projetos – EaD', 'icon_id' => 6],
            [
                'initialism' => 'GUAN',
                'name' => 'Gestão de Unidades de Alimentação e Nutrição',
                'icon_id' => 15,
            ],
            ['initialism' => 'GT', 'name' => 'Guia de Turismo', 'icon_id' => 24],
            ['initialism' => 'GTI', 'name' => 'Guia de Turismo Internacional', 'icon_id' => 24],
            ['initialism' => 'HIDR', 'name' => 'Hidrologia', 'icon_id' => 18],
            ['initialism' => 'HO', 'name' => 'Higiene Ocupacional', 'icon_id' => 23],
            ['initialism' => 'HOSP', 'name' => 'Hospedagem', 'icon_id' => 24],
            ['initialism' => 'INFO', 'name' => 'Informática', 'icon_id' => 1],
            ['initialism' => 'IPI', 'name' => 'Informática para Internet', 'icon_id' => 2],
            ['initialism' => 'IM', 'name' => 'Instrumento Musical', 'icon_id' => 21],
            ['initialism' => 'JAVAWR', 'name' => 'JAVA-WR', 'icon_id' => 1],
            ['initialism' => 'LAZE', 'name' => 'Lazer', 'icon_id' => 21],
            [
                'initialism' => 'LGG',
                'name' => 'Ensino Médio com ênfase em Linguagens e suas Tecnologias',
                'icon_id' => 0,
            ],
            ['initialism' => 'LOG', 'name' => 'Logística', 'icon_id' => 9],
            ['initialism' => 'LR', 'name' => 'Logística Reversa', 'icon_id' => 9],
            ['initialism' => 'MAUT', 'name' => 'Manutenção Automotiva', 'icon_id' => 11],
            ['initialism' => 'MMP', 'name' => 'Manutenção de Máquinas Pesadas', 'icon_id' => 11],
            [
                'initialism' => 'MSI',
                'name' => 'Manutenção e Suporte em Informática',
                'icon_id' => 4,
            ],
            ['initialism' => 'MKT', 'name' => 'Marketing', 'icon_id' => 8],
            [
                'initialism' => 'MAT',
                'name' => 'Ensino Médio com ênfase em Matemática e suas Tecnologias',
                'icon_id' => 0,
            ],
            ['initialism' => 'MEC', 'name' => 'Mecânica', 'icon_id' => 11],
            ['initialism' => 'MECA', 'name' => 'Mecanização Agrícola', 'icon_id' => 16],
            ['initialism' => 'MTR', 'name' => 'Mecatrônica', 'icon_id' => 13],
            ['initialism' => 'MA', 'name' => 'Meio Ambiente', 'icon_id' => 16],
            ['initialism' => 'MET', 'name' => 'Metalurgia', 'icon_id' => 11],
            ['initialism' => 'MINE', 'name' => 'Mineração', 'icon_id' => 17],
            ['initialism' => 'MV', 'name' => 'Modelagem do Vestuário', 'icon_id' => 19],
            ['initialism' => 'MOVE', 'name' => 'Móveis', 'icon_id' => 19],
            ['initialism' => 'MULT', 'name' => 'Multimídia', 'icon_id' => 20],
            ['initialism' => 'MUSE', 'name' => 'Museologia', 'icon_id' => 21],
            ['initialism' => 'ND', 'name' => 'Nutrição e Dietética', 'icon_id' => 22],
            ['initialism' => 'ONCO', 'name' => 'Oncologia', 'icon_id' => 22],
            [
                'initialism' => 'OEC',
                'name' => 'Organização de Eventos Corporativos',
                'icon_id' => 21,
            ],
            ['initialism' => 'OE', 'name' => 'Organização Esportiva', 'icon_id' => 21],
            ['initialism' => 'OP', 'name' => 'Órteses e Próteses', 'icon_id' => 22],
            ['initialism' => 'PAIS', 'name' => 'Paisagismo', 'icon_id' => 16],
            ['initialism' => 'PC', 'name' => 'Panificação e Confeitaria', 'icon_id' => 15],
            ['initialism' => 'PORT', 'name' => 'Portos', 'icon_id' => 9],
            ['initialism' => 'PF', 'name' => 'Processos Fotográficos', 'icon_id' => 20],
            ['initialism' => 'PRCU', 'name' => 'Produção Cultural', 'icon_id' => 21],
            ['initialism' => 'PAV', 'name' => 'Produção de Áudio e Vídeo', 'icon_id' => 20],
            ['initialism' => 'PCA', 'name' => 'Produção de Cana de Açúcar', 'icon_id' => 16],
            ['initialism' => 'PJD', 'name' => 'Programação de Jogos Digitais', 'icon_id' => 5],
            ['initialism' => 'PD', 'name' => 'Prótese Dentária', 'icon_id' => 22],
            [
                'initialism' => 'PFEC',
                'name' => 'Prótese fixa com ênfase em cerâmica',
                'icon_id' => 22,
            ],
            ['initialism' => 'PO', 'name' => 'Prótese Ortodôntica', 'icon_id' => 22],
            ['initialism' => 'PSI', 'name' => 'Prótese Sobre Implantes', 'icon_id' => 22],
            ['initialism' => 'PUBL', 'name' => 'Publicidade', 'icon_id' => 8],
            ['initialism' => 'QUAL', 'name' => 'Qualidade', 'icon_id' => 6],
            ['initialism' => 'QUIM', 'name' => 'Química', 'icon_id' => 14],
            ['initialism' => 'RDCM', 'name' => 'Rádiocomunicação', 'icon_id' => 12],
            ['initialism' => 'RH', 'name' => 'Recursos Humanos', 'icon_id' => 7],
            ['initialism' => 'RC', 'name' => 'Redes de Computadores', 'icon_id' => 4],
            ['initialism' => 'REGE', 'name' => 'Regência', 'icon_id' => 21],
            ['initialism' => 'SANE', 'name' => 'Saneamento', 'icon_id' => 4],
            ['initialism' => 'SB', 'name' => 'Saúde Bucal', 'icon_id' => 22],
            ['initialism' => 'SDTR', 'name' => 'Saúde do Trabalhador', 'icon_id' => 22],
            ['initialism' => 'SEC', 'name' => 'Secretariado', 'icon_id' => 6],
            [
                'initialism' => 'SACQ',
                'name' =>
                    'Segurança do Alimento - Ênfase em Controle de Qualidade em Unidade de Alimentação e Nutrição',
                'icon_id' => 23,
            ],
            ['initialism' => 'ST', 'name' => 'Segurança do Trabalho', 'icon_id' => 23],
            [
                'initialism' => 'STCC',
                'name' => 'Segurança do Trabalho na Construção Civil',
                'icon_id' => 23,
            ],
            ['initialism' => 'SEGU', 'name' => 'Seguros', 'icon_id' => 10],
            ['initialism' => 'SRB', 'name' => 'Serviços de Restaurante e Bar', 'icon_id' => 15],
            ['initialism' => 'SJ', 'name' => 'Serviços Jurídicos', 'icon_id' => 6],
            ['initialism' => 'SP', 'name' => 'Serviços Públicos', 'icon_id' => 6],
            ['initialism' => 'SF', 'name' => 'Sistema Fotovoltaico', 'icon_id' => 13],
            ['initialism' => 'SER', 'name' => 'Sistemas de Energia Renovável', 'icon_id' => 13],
            ['initialism' => 'SOLD', 'name' => 'Soldagem', 'icon_id' => 11],
            [
                'initialism' => 'SMEI',
                'name' => 'Supervisão de Manutenção Elétrica Industrial',
                'icon_id' => 12,
            ],
            ['initialism' => 'TEAT', 'name' => 'Teatro', 'icon_id' => 21],
            ['initialism' => 'LEGI', 'name' => 'Legislativo', 'icon_id' => 6],
            ['initialism' => 'TELE', 'name' => 'Telecomunicações', 'icon_id' => 4],
            ['initialism' => 'TI', 'name' => 'Transações Imobiliárias', 'icon_id' => 6],
            ['initialism' => 'TM', 'name' => 'Transporte Metroferroviário', 'icon_id' => 9],
            ['initialism' => 'TR', 'name' => 'Transporte Rodoviário', 'icon_id' => 9],
            ['initialism' => 'TE', 'name' => 'Turismo de Experiência', 'icon_id' => 24],
            ['initialism' => 'TURR', 'name' => 'Turismo Receptivo', 'icon_id' => 24],
            [
                'initialism' => 'APH',
                'name' => 'Urgência e Emergência - APH (Atendimento Pré-Hospitalar)',
                'icon_id' => 22,
            ],
            ['initialism' => 'VEST', 'name' => 'Vestuário', 'icon_id' => 19],
            ['initialism' => 'VET', 'name' => 'Veterinária', 'icon_id' => 22],
            ['initialism' => 'VIDR', 'name' => 'Vidro', 'icon_id' => 14],
            ['initialism' => 'VE', 'name' => 'Viticultura e Enologia', 'icon_id' => 16],
            ['initialism' => 'ZOOT', 'name' => 'Zootecnia', 'icon_id' => 16],
        ];

        foreach (array_chunk($courses, 100) as $chunk) {
            DB::table('courses')->insert($chunk);
        }
    }
}
