<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtecSeeder extends Seeder
{
    public function run(): void
    {
        $etecs = [
            ['code' => 6, 'name' => 'Etec Polivalente de Americana'],
            ['code' => 7, 'name' => 'Etec Conselheiro Antônio Prado'],
            ['code' => 8, 'name' => 'Etec Vasco Antônio Venchiarutti'],
            ['code' => 9, 'name' => 'Etec João Baptista de Lima Figueiredo'],
            ['code' => 10, 'name' => 'Etec Lauro Gomes'],
            ['code' => 11, 'name' => 'Etec Jorge Street'],
            ['code' => 12, 'name' => 'Etec Prof. Camargo Aranha (Mooca)'],
            ['code' => 13, 'name' => 'Etec Getúlio Vargas (Ipiranga)'],
            ['code' => 14, 'name' => 'Etec Júlio de Mesquita'],
            ['code' => 15, 'name' => 'Etec Presidente Vargas'],
            ['code' => 16, 'name' => 'Etec Fernando Prestes'],
            ['code' => 17, 'name' => 'Etec Rubens de Faria e Souza'],
            ['code' => 18, 'name' => 'Etec São Paulo (Bom Retiro)'],
            ['code' => 19, 'name' => 'Etec Dr. Adail Nunes da Silva'],
            ['code' => 23, 'name' => 'Etec Albert Einstein (Casa Verde)'],
            ['code' => 24, 'name' => 'Etec Prefeito Alberto Feres'],
            ['code' => 25, 'name' => 'Etec Prof. Alcídio de Souza Prado'],
            ['code' => 26, 'name' => 'Etec Prof. Alfredo de Barros Santos'],
            ['code' => 27, 'name' => 'Etec Amim Jundi'],
            ['code' => 28, 'name' => 'Etec Sebastiana Augusta de Moraes'],
            ['code' => 29, 'name' => 'Etec Profª Anna de Oliveira Ferraz'],
            ['code' => 30, 'name' => 'Etec Antônio de Pádua Cardoso'],
            ['code' => 31, 'name' => 'Etec Antônio Devisate'],
            ['code' => 32, 'name' => 'Etec Prof. Dr. Antônio E. de Toledo'],
            ['code' => 33, 'name' => 'Etec Antonio Junqueira da Veiga'],
            ['code' => 34, 'name' => 'Etec Prof. Aprígio Gonzaga (Penha)'],
            ['code' => 35, 'name' => 'Etec Aristóteles Ferreira'],
            ['code' => 36, 'name' => 'Etec Prof. Armando Bayeux da Silva'],
            ['code' => 37, 'name' => 'Etec Frei Arnaldo Maria de Itaporanga'],
            ['code' => 38, 'name' => 'Etec Astor de Mattos Carvalho'],
            ['code' => 39, 'name' => 'Etec Augusto Tortolero Araújo'],
            ['code' => 40, 'name' => 'Etec Comendador João Rays'],
            ['code' => 41, 'name' => 'Etec Prof. Basílides de Godoy (Vila Leopoldina)'],
            ['code' => 42, 'name' => 'Etec Benedito Storani'],
            ['code' => 43, 'name' => 'Etec Bento Quirino'],
            ['code' => 44, 'name' => 'Etec Prof. Marcos Uchôas dos Santos Penchel'],
            ['code' => 45, 'name' => 'Etec Carlos de Campos (Brás)'],
            ['code' => 46, 'name' => 'Etec Prof. Carmelino Correa Junior'],
            ['code' => 47, 'name' => 'Etec Dr. Carolino da Motta e Silva'],
            ['code' => 48, 'name' => 'Etec Cônego José Bento'],
            ['code' => 49, 'name' => 'Etec Dr. Dario Pacheco Pedroso'],
            ['code' => 50, 'name' => 'Etec Dr. Demétrio Azevedo Jr.'],
            ['code' => 51, 'name' => 'Etec Dr. Domingos Minicucci Filho'],
            ['code' => 52, 'name' => 'Etec Profª Carmelina Barbosa'],
            ['code' => 53, 'name' => 'Etec Prof. Edson Galvão'],
            ['code' => 54, 'name' => 'Etec Elias Nechar'],
            ['code' => 55, 'name' => 'Etec Prof. Eudécio Luiz Vicente'],
            ['code' => 56, 'name' => 'Etec Cel. Fernando Febeliano da Costa'],
            ['code' => 57, 'name' => 'Etec Prof. Francisco dos Santos'],
            ['code' => 58, 'name' => 'Etec Dep. Francisco Franco'],
            ['code' => 59, 'name' => 'Etec Dr. Francisco Nogueira de Lima'],
            ['code' => 60, 'name' => 'Etec Francisco Garcia'],
            ['code' => 61, 'name' => 'Etec Guaracy Silveira (Pinheiros)'],
            ['code' => 62, 'name' => 'Etec Profª Helcy Moreira Martins Aguiar'],
            ['code' => 63, 'name' => 'Etec Eng. Herval Bellusci'],
            ['code' => 64, 'name' => 'Etec Prof. Horácio Augusto da Silveira (Vila Guilherme)'],
            ['code' => 65, 'name' => 'Etec de Ilha Solteira'],
            ['code' => 66, 'name' => 'Etec Jacinto Ferreira de Sá'],
            ['code' => 67, 'name' => 'Etec João Belarmino'],
            ['code' => 68, 'name' => 'Etec João Gomes de Araújo'],
            ['code' => 69, 'name' => 'Etec João Jorge Geraissate'],
            ['code' => 70, 'name' => 'Etec Joaquim Ferreira do Amaral'],
            ['code' => 71, 'name' => 'Etec Dr. José Coury'],
            ['code' => 72, 'name' => 'Etec Pref. José Esteves'],
            ['code' => 73, 'name' => 'Etec Dr. José Luiz Viana Coutinho'],
            ['code' => 74, 'name' => 'Etec José Martimiano da Silva'],
            ['code' => 75, 'name' => 'Etec Padre José Nunes Dias'],
            ['code' => 76, 'name' => 'Etec José Rocha Mendes (Vila Prudente)'],
            ['code' => 77, 'name' => 'Etec Prof. José Sant’Ana de Castro'],
            ['code' => 78, 'name' => 'Etec Dr. Júlio Cardoso'],
            ['code' => 79, 'name' => 'Etec Laurindo Alves de Queiroz'],
            ['code' => 80, 'name' => 'Etec Dr. Luiz César Couto'],
            ['code' => 81, 'name' => 'Etec Prof. Luiz Pires Barbosa'],
            ['code' => 82, 'name' => 'Etec Machado de Assis'],
            ['code' => 83, 'name' => 'Etec Manoel dos Reis Araújo'],
            ['code' => 84, 'name' => 'Etec Orlando Quagliato'],
            ['code' => 85, 'name' => 'Etec Martin Luther King (Tatuapé)'],
            ['code' => 86, 'name' => 'Etec Martinho Di Ciero'],
            ['code' => 87, 'name' => 'Etec Prof. Matheus Leite de Abreu'],
            ['code' => 88, 'name' => 'Etec Monsenhor Antônio Magliano'],
            ['code' => 89, 'name' => 'Etec Eng. Agrônomo Narciso de Medeiros'],
            ['code' => 90, 'name' => 'Etec Prof. Urias Ferreira'],
            ['code' => 91, 'name' => 'Etec Paulino Botelho'],
            ['code' => 92, 'name' => 'Etec Paulo Guerreiro Franco'],
            ['code' => 93, 'name' => 'Etec Dep. Paulo Ornellas Carvalho de Barros'],
            ['code' => 94, 'name' => 'Etec Pedro Badran'],
            ['code' => 95, 'name' => 'Etec Pedro D’Arcádia Neto'],
            ['code' => 96, 'name' => 'Etec Pedro Ferreira Alves'],
            ['code' => 97, 'name' => 'Etec Prof. Pedro Leme Brisolla Sobrinho'],
            ['code' => 98, 'name' => 'Etec Philadelpho Gouvêa Netto'],
            ['code' => 99, 'name' => 'Etec Prof. Milton Gazzetti'],
            ['code' => 100, 'name' => 'Etec Rosa Perrone Scavone'],
            ['code' => 101, 'name' => 'Etec Sales Gomes'],
            ['code' => 102, 'name' => 'Etec Dona Sebastiana de Barros'],
            ['code' => 103, 'name' => 'Etec Sylvio de Mattos Carvalho'],
            ['code' => 104, 'name' => 'Etec Trajano Camargo'],
            ['code' => 107, 'name' => 'Etec Adolpho Berezin'],
            ['code' => 108, 'name' => 'Etec Cel. Raphael Brandão'],
            ['code' => 110, 'name' => 'Etec Dep. Salim Sedeh'],
            ['code' => 115, 'name' => 'Etec de Hortolândia'],
            ['code' => 116, 'name' => 'Etec de São Roque'],
            ['code' => 117, 'name' => 'Etec Prof. Dr. José Dagnoni'],
            ['code' => 118, 'name' => 'Etec de Guaianazes (Guaianazes)'],
            ['code' => 122, 'name' => 'Etec Dona Escolástica Rosa'],
            ['code' => 123, 'name' => 'Etec Dr. Renato Cordeiro'],
            ['code' => 124, 'name' => 'Etec Dr. Celso Charuri'],
            ['code' => 125, 'name' => 'Etec Dr. Geraldo José Rodrigues Alckmin'],
            ['code' => 128, 'name' => 'Etec de Mauá'],
            ['code' => 134, 'name' => 'Etec Carolina Carinhato Sampaio (Jardim São Luís)'],
            ['code' => 135, 'name' => 'Etec Rodrigues de Abreu'],
            ['code' => 136, 'name' => 'Etec Prof. Massuyuki Kawano'],
            ['code' => 138, 'name' => 'Etec Prof. Armando José Farinazzo'],
            ['code' => 139, 'name' => 'Etec Tenente Aviador Gustavo Klug'],
            ['code' => 140, 'name' => 'Etec Profª Terezinha Monteiro dos Santos'],
            ['code' => 141, 'name' => 'Etec Profª Maria Cristina Medeiros'],
            ['code' => 142, 'name' => 'Etec Dr. Emilio Hernandez Aguilar'],
            ['code' => 144, 'name' => 'Etec de Carapicuíba'],
            ['code' => 145, 'name' => 'Etec Prof. Fausto Mazzola'],
            ['code' => 147, 'name' => 'Etec Prof. Carmine Biagio Tundisi'],
            ['code' => 148, 'name' => 'Etec de Lins'],
            ['code' => 149, 'name' => 'Etec Prof. André Bogasian'],
            ['code' => 150, 'name' => 'Etec Prof. Rodolpho José Del Guerra'],
            ['code' => 151, 'name' => 'Etec Prof. Ídio Zucchi'],
            ['code' => 152, 'name' => 'Etec Alberto Santos Dumont'],
            ['code' => 153, 'name' => 'Etec de Praia Grande'],
            ['code' => 154, 'name' => 'Etec Dra. Maria Augusta Saraiva (Campos Elíseos)'],
            ['code' => 156, 'name' => 'Etec Profª Nair Luccas Ribeiro'],
            ['code' => 158, 'name' => 'Etec de Itanhaém'],
            ['code' => 159, 'name' => 'Etec Parque da Juventude (Santana)'],
            ['code' => 161, 'name' => 'Etec Vereador e Vice Prefeito Sérgio da Fonseca'],
            ['code' => 162, 'name' => 'Etec Waldyr Duron Junior'],
            ['code' => 164, 'name' => 'Etec Prof. Mário Antônio Verza'],
            ['code' => 165, 'name' => 'Etec de Araçatuba'],
            ['code' => 166, 'name' => 'Etec Juscelino Kubitschek de Oliveira'],
            ['code' => 169, 'name' => 'Etec de Itaquera (Cohab 2)'],
            ['code' => 170, 'name' => 'Etec de Ferraz de Vasconcelos'],
            ['code' => 172, 'name' => 'Etec de Sapopemba (Sapopemba)'],
            ['code' => 179, 'name' => 'Etec de Vargem Grande do Sul'],
            ['code' => 180, 'name' => 'Etec de Artes (Santana)'],
            ['code' => 181, 'name' => 'Etec de Cubatão'],
            ['code' => 185, 'name' => 'Etec de Vila Formosa (Vila Formosa)'],
            [
                'code' => 186,
                'name' => 'Etec Tereza Aparecida Cardoso Nunes de Oliveira (Arthur Alvim)',
            ],
            ['code' => 187, 'name' => 'Etec Profª Ermelinda Giannini Teixeira'],
            ['code' => 188, 'name' => 'Etec de São Sebastião'],
            ['code' => 190, 'name' => 'Etec de Suzano'],
            ['code' => 191, 'name' => 'Etec Gino Rezaghi'],
            ['code' => 193, 'name' => 'Etec Dep. Ary de Camargo Pedroso'],
            ['code' => 194, 'name' => 'Etec Dra. Ruth Cardoso'],
            ['code' => 195, 'name' => 'Etec Profª Ilza Nascimento Pintus'],
            ['code' => 197, 'name' => 'Etec Prof. Elias Miguel Júnior'],
            ['code' => 198, 'name' => 'Etec de Monte Mor'],
            ['code' => 199, 'name' => 'Etec de Cidade Tiradentes (Cidade Tiradentes)'],
            ['code' => 200, 'name' => 'Etec Takashi Morita (Santo Amaro)'],
            ['code' => 201, 'name' => 'Etec de Campo Limpo Paulista'],
            ['code' => 202, 'name' => 'Etec Prof. Jadyr Salles'],
            ['code' => 203, 'name' => 'Etec de Piedade'],
            ['code' => 205, 'name' => 'Etec de Heliópolis – Arquiteto Ruy Ohtake'],
            ['code' => 206, 'name' => 'Etec Euro Albino de Souza'],
            ['code' => 207, 'name' => 'Etec Prof. Adhemar Batista Heméritas (Vila Formosa)'],
            ['code' => 208, 'name' => 'Etec de Tiquatira (Penha)'],
            ['code' => 210, 'name' => 'Etec de Poá'],
            ['code' => 211, 'name' => 'Etec da Zona Leste (Cidade A. E. Carvalho)'],
            ['code' => 212, 'name' => 'Etec Profª Marines Teodoro de Freitas Almeida'],
            ['code' => 213, 'name' => 'Etec de Caraguatatuba'],
            ['code' => 214, 'name' => 'Etec Angelo Cavalheiro'],
            ['code' => 215, 'name' => 'Etec Arnaldo Pereira Cheregatti'],
            ['code' => 218, 'name' => 'Etec João Maria Stevanatto'],
            ['code' => 219, 'name' => 'Etec de Santa Isabel'],
            ['code' => 220, 'name' => 'Etec Parque Belém (Parque Belém)'],
            ['code' => 221, 'name' => 'Etec Jardim Ângela (Jardim Ângela)'],
            ['code' => 222, 'name' => 'Etec de Cotia'],
            ['code' => 223, 'name' => 'Etec Cepam (Butantã)'],
            ['code' => 224, 'name' => 'Etec Abdias do Nascimento (Paraisópolis)'],
            ['code' => 225, 'name' => 'Etec Raposo Tavares (Raposo Tavares)'],
            ['code' => 226, 'name' => 'Etec Gildo Marçal Bezerra Brandão (Perus)'],
            ['code' => 227, 'name' => 'Etec São Mateus (São Mateus)'],
            ['code' => 228, 'name' => 'Etec Jaraguá (Jaraguá)'],
            ['code' => 229, 'name' => 'Etec Paulistano (Freguesia do Ó)'],
            ['code' => 230, 'name' => 'Etec Uirapuru (Uirapuru)'],
            ['code' => 231, 'name' => 'Etec de Francisco Morato'],
            ['code' => 232, 'name' => 'Etec Prof. José Carlos Seno Junior'],
            ['code' => 233, 'name' => 'Etec Prof. José Ignácio Azevedo Filho'],
            ['code' => 234, 'name' => 'Etec Ferrucio Humberto Gazzetta'],
            ['code' => 235, 'name' => 'Etec de Mairinque'],
            ['code' => 236, 'name' => 'Etec Gustavo Teixeira'],
            ['code' => 237, 'name' => 'Etec de Santa Rosa de Viterbo'],
            ['code' => 238, 'name' => 'Etec Irmã Agostina (Capela do Socorro)'],
            ['code' => 239, 'name' => 'Etec de Registro'],
            ['code' => 240, 'name' => 'Etec Padre Carlos Leôncio da Silva'],
            ['code' => 241, 'name' => 'Etec de Embu'],
            ['code' => 242, 'name' => 'Etec Dr. Celso Giglio'],
            ['code' => 243, 'name' => 'Etec de Itararé'],
            ['code' => 244, 'name' => 'Etec Cidade do Livro'],
            ['code' => 245, 'name' => 'Etec Antônio Furlan'],
            ['code' => 246, 'name' => 'Etec Dr. Nelson Alves Vianna'],
            ['code' => 247, 'name' => 'Etec Mandaqui (Mandaqui)'],
            ['code' => 248, 'name' => 'Etec de Cerquilho'],
            ['code' => 249, 'name' => 'Etec de Itaquaquecetuba'],
            ['code' => 252, 'name' => 'Etec Prof. Adolpho Arruda Mello '],
            ['code' => 253, 'name' => 'Etec Jornalista Roberto Marinho (Brooklin)'],
            [
                'code' => 254,
                'name' => 'Etec Profª Dra. Doroti Quiomi Kanashiro Toyohara (Pirituba)',
            ],
            ['code' => 255, 'name' => 'Etec Alcides Cestari'],
            ['code' => 256, 'name' => 'Etec Bento Carlos Botelho do Amaral'],
            ['code' => 260, 'name' => 'Etec Santa Ifigênia (Santa Ifigênia)'],
            ['code' => 261, 'name' => 'Etec Darcy Pereira de Moraes'],
            ['code' => 262, 'name' => 'Etec Bartolomeu Bueno da Silva – Anhanguera'],
            ['code' => 263, 'name' => 'Etec de Ibaté'],
            ['code' => 264, 'name' => 'Etec Armando Pannunzio'],
            ['code' => 266, 'name' => 'Etec de Peruíbe'],
            ['code' => 267, 'name' => 'Etec de Esportes – Curt Walter Otto Baumgart (Vila Maria)'],
            ['code' => 268, 'name' => 'Etec Prefeito Braz Paschoalin'],
            ['code' => 271, 'name' => 'Etec de Mairiporã'],
            ['code' => 273, 'name' => 'Etec Sebrae (Campos Elíseos)'],
            ['code' => 274, 'name' => 'Etec Profª Luzia Maria Machado'],
            ['code' => 277, 'name' => 'Etec de Santa Fé do Sul'],
            ['code' => 279, 'name' => 'Etec Paulo do Carmo Monteiro'],
            ['code' => 281, 'name' => 'Etec de Apiaí'],
            ['code' => 282, 'name' => 'Etec Rio Grande da Serra'],
            ['code' => 285, 'name' => 'Etec Itaquera II (Itaquera)'],
            ['code' => 287, 'name' => 'Etec João Elias Margutti'],
            ['code' => 289, 'name' => 'Etec de Porto Feliz'],
            ['code' => 293, 'name' => 'Etec de Taboão da Serra'],
            ['code' => 295, 'name' => 'Etec de Guarulhos'],
            ['code' => 300, 'name' => 'Etec José Miguel Soares'],
            ['code' => 302, 'name' => 'Etec Sumaré Cidade Orquídea'],
            ['code' => 303, 'name' => 'Etec de Cravinhos'],
            ['code' => 304, 'name' => 'Etec de Guaíra'],
            ['code' => 306, 'name' => 'Etec de Bragança Paulista'],
            ['code' => 314, 'name' => 'Etec Vereador Valdivino Antônio Marcusso'],
        ];

        $now = now();

        $rows = array_map(function ($etec) use ($now) {
            return [
                'code' => $etec['code'],
                'name' => $etec['name'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $etecs);

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('etecs')->insert($chunk);
        }
    }
}
