<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtecSeeder extends Seeder
{
    public function run(): void
    {
        $etecs = [
            ['codigo' => 6, 'nome' => 'Etec Polivalente de Americana'],
            ['codigo' => 7, 'nome' => 'Etec Conselheiro Antônio Prado'],
            ['codigo' => 8, 'nome' => 'Etec Vasco Antônio Venchiarutti'],
            ['codigo' => 9, 'nome' => 'Etec João Baptista de Lima Figueiredo'],
            ['codigo' => 10, 'nome' => 'Etec Lauro Gomes'],
            ['codigo' => 11, 'nome' => 'Etec Jorge Street'],
            ['codigo' => 12, 'nome' => 'Etec Prof. Camargo Aranha (Mooca)'],
            ['codigo' => 13, 'nome' => 'Etec Getúlio Vargas (Ipiranga)'],
            ['codigo' => 14, 'nome' => 'Etec Júlio de Mesquita'],
            ['codigo' => 15, 'nome' => 'Etec Presidente Vargas'],
            ['codigo' => 16, 'nome' => 'Etec Fernando Prestes'],
            ['codigo' => 17, 'nome' => 'Etec Rubens de Faria e Souza'],
            ['codigo' => 18, 'nome' => 'Etec São Paulo (Bom Retiro)'],
            ['codigo' => 19, 'nome' => 'Etec Dr. Adail Nunes da Silva'],
            ['codigo' => 23, 'nome' => 'Etec Albert Einstein (Casa Verde)'],
            ['codigo' => 24, 'nome' => 'Etec Prefeito Alberto Feres'],
            ['codigo' => 25, 'nome' => 'Etec Prof. Alcídio de Souza Prado'],
            ['codigo' => 26, 'nome' => 'Etec Prof. Alfredo de Barros Santos'],
            ['codigo' => 27, 'nome' => 'Etec Amim Jundi'],
            ['codigo' => 28, 'nome' => 'Etec Sebastiana Augusta de Moraes'],
            ['codigo' => 29, 'nome' => 'Etec Profª Anna de Oliveira Ferraz'],
            ['codigo' => 30, 'nome' => 'Etec Antônio de Pádua Cardoso'],
            ['codigo' => 31, 'nome' => 'Etec Antônio Devisate'],
            ['codigo' => 32, 'nome' => 'Etec Prof. Dr. Antônio E. de Toledo'],
            ['codigo' => 33, 'nome' => 'Etec Antonio Junqueira da Veiga'],
            ['codigo' => 34, 'nome' => 'Etec Prof. Aprígio Gonzaga (Penha)'],
            ['codigo' => 35, 'nome' => 'Etec Aristóteles Ferreira'],
            ['codigo' => 36, 'nome' => 'Etec Prof. Armando Bayeux da Silva'],
            ['codigo' => 37, 'nome' => 'Etec Frei Arnaldo Maria de Itaporanga'],
            ['codigo' => 38, 'nome' => 'Etec Astor de Mattos Carvalho'],
            ['codigo' => 39, 'nome' => 'Etec Augusto Tortolero Araújo'],
            ['codigo' => 40, 'nome' => 'Etec Comendador João Rays'],
            ['codigo' => 41, 'nome' => 'Etec Prof. Basílides de Godoy (Vila Leopoldina)'],
            ['codigo' => 42, 'nome' => 'Etec Benedito Storani'],
            ['codigo' => 43, 'nome' => 'Etec Bento Quirino'],
            ['codigo' => 44, 'nome' => 'Etec Prof. Marcos Uchôas dos Santos Penchel'],
            ['codigo' => 45, 'nome' => 'Etec Carlos de Campos (Brás)'],
            ['codigo' => 46, 'nome' => 'Etec Prof. Carmelino Correa Junior'],
            ['codigo' => 47, 'nome' => 'Etec Dr. Carolino da Motta e Silva'],
            ['codigo' => 48, 'nome' => 'Etec Cônego José Bento'],
            ['codigo' => 49, 'nome' => 'Etec Dr. Dario Pacheco Pedroso'],
            ['codigo' => 50, 'nome' => 'Etec Dr. Demétrio Azevedo Jr.'],
            ['codigo' => 51, 'nome' => 'Etec Dr. Domingos Minicucci Filho'],
            ['codigo' => 52, 'nome' => 'Etec Profª Carmelina Barbosa'],
            ['codigo' => 53, 'nome' => 'Etec Prof. Edson Galvão'],
            ['codigo' => 54, 'nome' => 'Etec Elias Nechar'],
            ['codigo' => 55, 'nome' => 'Etec Prof. Eudécio Luiz Vicente'],
            ['codigo' => 56, 'nome' => 'Etec Cel. Fernando Febeliano da Costa'],
            ['codigo' => 57, 'nome' => 'Etec Prof. Francisco dos Santos'],
            ['codigo' => 58, 'nome' => 'Etec Dep. Francisco Franco'],
            ['codigo' => 59, 'nome' => 'Etec Dr. Francisco Nogueira de Lima'],
            ['codigo' => 60, 'nome' => 'Etec Francisco Garcia'],
            ['codigo' => 61, 'nome' => 'Etec Guaracy Silveira (Pinheiros)'],
            ['codigo' => 62, 'nome' => 'Etec Profª Helcy Moreira Martins Aguiar'],
            ['codigo' => 63, 'nome' => 'Etec Eng. Herval Bellusci'],
            ['codigo' => 64, 'nome' => 'Etec Prof. Horácio Augusto da Silveira (Vila Guilherme)'],
            ['codigo' => 65, 'nome' => 'Etec de Ilha Solteira'],
            ['codigo' => 66, 'nome' => 'Etec Jacinto Ferreira de Sá'],
            ['codigo' => 67, 'nome' => 'Etec João Belarmino'],
            ['codigo' => 68, 'nome' => 'Etec João Gomes de Araújo'],
            ['codigo' => 69, 'nome' => 'Etec João Jorge Geraissate'],
            ['codigo' => 70, 'nome' => 'Etec Joaquim Ferreira do Amaral'],
            ['codigo' => 71, 'nome' => 'Etec Dr. José Coury'],
            ['codigo' => 72, 'nome' => 'Etec Pref. José Esteves'],
            ['codigo' => 73, 'nome' => 'Etec Dr. José Luiz Viana Coutinho'],
            ['codigo' => 74, 'nome' => 'Etec José Martimiano da Silva'],
            ['codigo' => 75, 'nome' => 'Etec Padre José Nunes Dias'],
            ['codigo' => 76, 'nome' => 'Etec José Rocha Mendes (Vila Prudente)'],
            ['codigo' => 77, 'nome' => 'Etec Prof. José Sant’Ana de Castro'],
            ['codigo' => 78, 'nome' => 'Etec Dr. Júlio Cardoso'],
            ['codigo' => 79, 'nome' => 'Etec Laurindo Alves de Queiroz'],
            ['codigo' => 80, 'nome' => 'Etec Dr. Luiz César Couto'],
            ['codigo' => 81, 'nome' => 'Etec Prof. Luiz Pires Barbosa'],
            ['codigo' => 82, 'nome' => 'Etec Machado de Assis'],
            ['codigo' => 83, 'nome' => 'Etec Manoel dos Reis Araújo'],
            ['codigo' => 84, 'nome' => 'Etec Orlando Quagliato'],
            ['codigo' => 85, 'nome' => 'Etec Martin Luther King (Tatuapé)'],
            ['codigo' => 86, 'nome' => 'Etec Martinho Di Ciero'],
            ['codigo' => 87, 'nome' => 'Etec Prof. Matheus Leite de Abreu'],
            ['codigo' => 88, 'nome' => 'Etec Monsenhor Antônio Magliano'],
            ['codigo' => 89, 'nome' => 'Etec Eng. Agrônomo Narciso de Medeiros'],
            ['codigo' => 90, 'nome' => 'Etec Prof. Urias Ferreira'],
            ['codigo' => 91, 'nome' => 'Etec Paulino Botelho'],
            ['codigo' => 92, 'nome' => 'Etec Paulo Guerreiro Franco'],
            ['codigo' => 93, 'nome' => 'Etec Dep. Paulo Ornellas Carvalho de Barros'],
            ['codigo' => 94, 'nome' => 'Etec Pedro Badran'],
            ['codigo' => 95, 'nome' => 'Etec Pedro D’Arcádia Neto'],
            ['codigo' => 96, 'nome' => 'Etec Pedro Ferreira Alves'],
            ['codigo' => 97, 'nome' => 'Etec Prof. Pedro Leme Brisolla Sobrinho'],
            ['codigo' => 98, 'nome' => 'Etec Philadelpho Gouvêa Netto'],
            ['codigo' => 99, 'nome' => 'Etec Prof. Milton Gazzetti'],
            ['codigo' => 100, 'nome' => 'Etec Rosa Perrone Scavone'],
            ['codigo' => 101, 'nome' => 'Etec Sales Gomes'],
            ['codigo' => 102, 'nome' => 'Etec Dona Sebastiana de Barros'],
            ['codigo' => 103, 'nome' => 'Etec Sylvio de Mattos Carvalho'],
            ['codigo' => 104, 'nome' => 'Etec Trajano Camargo'],
            ['codigo' => 107, 'nome' => 'Etec Adolpho Berezin'],
            ['codigo' => 108, 'nome' => 'Etec Cel. Raphael Brandão'],
            ['codigo' => 110, 'nome' => 'Etec Dep. Salim Sedeh'],
            ['codigo' => 115, 'nome' => 'Etec de Hortolândia'],
            ['codigo' => 116, 'nome' => 'Etec de São Roque'],
            ['codigo' => 117, 'nome' => 'Etec Prof. Dr. José Dagnoni'],
            ['codigo' => 118, 'nome' => 'Etec de Guaianazes (Guaianazes)'],
            ['codigo' => 122, 'nome' => 'Etec Dona Escolástica Rosa'],
            ['codigo' => 123, 'nome' => 'Etec Dr. Renato Cordeiro'],
            ['codigo' => 124, 'nome' => 'Etec Dr. Celso Charuri'],
            ['codigo' => 125, 'nome' => 'Etec Dr. Geraldo José Rodrigues Alckmin'],
            ['codigo' => 128, 'nome' => 'Etec de Mauá'],
            ['codigo' => 134, 'nome' => 'Etec Carolina Carinhato Sampaio (Jardim São Luís)'],
            ['codigo' => 135, 'nome' => 'Etec Rodrigues de Abreu'],
            ['codigo' => 136, 'nome' => 'Etec Prof. Massuyuki Kawano'],
            ['codigo' => 138, 'nome' => 'Etec Prof. Armando José Farinazzo'],
            ['codigo' => 139, 'nome' => 'Etec Tenente Aviador Gustavo Klug'],
            ['codigo' => 140, 'nome' => 'Etec Profª Terezinha Monteiro dos Santos'],
            ['codigo' => 141, 'nome' => 'Etec Profª Maria Cristina Medeiros'],
            ['codigo' => 142, 'nome' => 'Etec Dr. Emilio Hernandez Aguilar'],
            ['codigo' => 144, 'nome' => 'Etec de Carapicuíba'],
            ['codigo' => 145, 'nome' => 'Etec Prof. Fausto Mazzola'],
            ['codigo' => 147, 'nome' => 'Etec Prof. Carmine Biagio Tundisi'],
            ['codigo' => 148, 'nome' => 'Etec de Lins'],
            ['codigo' => 149, 'nome' => 'Etec Prof. André Bogasian'],
            ['codigo' => 150, 'nome' => 'Etec Prof. Rodolpho José Del Guerra'],
            ['codigo' => 151, 'nome' => 'Etec Prof. Ídio Zucchi'],
            ['codigo' => 152, 'nome' => 'Etec Alberto Santos Dumont'],
            ['codigo' => 153, 'nome' => 'Etec de Praia Grande'],
            ['codigo' => 154, 'nome' => 'Etec Dra. Maria Augusta Saraiva (Campos Elíseos)'],
            ['codigo' => 156, 'nome' => 'Etec Profª Nair Luccas Ribeiro'],
            ['codigo' => 158, 'nome' => 'Etec de Itanhaém'],
            ['codigo' => 159, 'nome' => 'Etec Parque da Juventude (Santana)'],
            ['codigo' => 161, 'nome' => 'Etec Vereador e Vice Prefeito Sérgio da Fonseca'],
            ['codigo' => 162, 'nome' => 'Etec Waldyr Duron Junior'],
            ['codigo' => 164, 'nome' => 'Etec Prof. Mário Antônio Verza'],
            ['codigo' => 165, 'nome' => 'Etec de Araçatuba'],
            ['codigo' => 166, 'nome' => 'Etec Juscelino Kubitschek de Oliveira'],
            ['codigo' => 169, 'nome' => 'Etec de Itaquera (Cohab 2)'],
            ['codigo' => 170, 'nome' => 'Etec de Ferraz de Vasconcelos'],
            ['codigo' => 172, 'nome' => 'Etec de Sapopemba (Sapopemba)'],
            ['codigo' => 179, 'nome' => 'Etec de Vargem Grande do Sul'],
            ['codigo' => 180, 'nome' => 'Etec de Artes (Santana)'],
            ['codigo' => 181, 'nome' => 'Etec de Cubatão'],
            ['codigo' => 185, 'nome' => 'Etec de Vila Formosa (Vila Formosa)'],
            ['codigo' => 186, 'nome' => 'Etec Tereza Aparecida Cardoso Nunes de Oliveira (Arthur Alvim)'],
            ['codigo' => 187, 'nome' => 'Etec Profª Ermelinda Giannini Teixeira'],
            ['codigo' => 188, 'nome' => 'Etec de São Sebastião'],
            ['codigo' => 190, 'nome' => 'Etec de Suzano'],
            ['codigo' => 191, 'nome' => 'Etec Gino Rezaghi'],
            ['codigo' => 193, 'nome' => 'Etec Dep. Ary de Camargo Pedroso'],
            ['codigo' => 194, 'nome' => 'Etec Dra. Ruth Cardoso'],
            ['codigo' => 195, 'nome' => 'Etec Profª Ilza Nascimento Pintus'],
            ['codigo' => 197, 'nome' => 'Etec Prof. Elias Miguel Júnior'],
            ['codigo' => 198, 'nome' => 'Etec de Monte Mor'],
            ['codigo' => 199, 'nome' => 'Etec de Cidade Tiradentes (Cidade Tiradentes)'],
            ['codigo' => 200, 'nome' => 'Etec Takashi Morita (Santo Amaro)'],
            ['codigo' => 201, 'nome' => 'Etec de Campo Limpo Paulista'],
            ['codigo' => 202, 'nome' => 'Etec Prof. Jadyr Salles'],
            ['codigo' => 203, 'nome' => 'Etec de Piedade'],
            ['codigo' => 205, 'nome' => 'Etec de Heliópolis – Arquiteto Ruy Ohtake'],
            ['codigo' => 206, 'nome' => 'Etec Euro Albino de Souza'],
            ['codigo' => 207, 'nome' => 'Etec Prof. Adhemar Batista Heméritas (Vila Formosa)'],
            ['codigo' => 208, 'nome' => 'Etec de Tiquatira (Penha)'],
            ['codigo' => 210, 'nome' => 'Etec de Poá'],
            ['codigo' => 211, 'nome' => 'Etec da Zona Leste (Cidade A. E. Carvalho)'],
            ['codigo' => 212, 'nome' => 'Etec Profª Marines Teodoro de Freitas Almeida'],
            ['codigo' => 213, 'nome' => 'Etec de Caraguatatuba'],
            ['codigo' => 214, 'nome' => 'Etec Angelo Cavalheiro'],
            ['codigo' => 215, 'nome' => 'Etec Arnaldo Pereira Cheregatti'],
            ['codigo' => 218, 'nome' => 'Etec João Maria Stevanatto'],
            ['codigo' => 219, 'nome' => 'Etec de Santa Isabel'],
            ['codigo' => 220, 'nome' => 'Etec Parque Belém (Parque Belém)'],
            ['codigo' => 221, 'nome' => 'Etec Jardim Ângela (Jardim Ângela)'],
            ['codigo' => 222, 'nome' => 'Etec de Cotia'],
            ['codigo' => 223, 'nome' => 'Etec Cepam (Butantã)'],
            ['codigo' => 224, 'nome' => 'Etec Abdias do Nascimento (Paraisópolis)'],
            ['codigo' => 225, 'nome' => 'Etec Raposo Tavares (Raposo Tavares)'],
            ['codigo' => 226, 'nome' => 'Etec Gildo Marçal Bezerra Brandão (Perus)'],
            ['codigo' => 227, 'nome' => 'Etec São Mateus (São Mateus)'],
            ['codigo' => 228, 'nome' => 'Etec Jaraguá (Jaraguá)'],
            ['codigo' => 229, 'nome' => 'Etec Paulistano (Freguesia do Ó)'],
            ['codigo' => 230, 'nome' => 'Etec Uirapuru (Uirapuru)'],
            ['codigo' => 231, 'nome' => 'Etec de Francisco Morato'],
            ['codigo' => 232, 'nome' => 'Etec Prof. José Carlos Seno Junior'],
            ['codigo' => 233, 'nome' => 'Etec Prof. José Ignácio Azevedo Filho'],
            ['codigo' => 234, 'nome' => 'Etec Ferrucio Humberto Gazzetta'],
            ['codigo' => 235, 'nome' => 'Etec de Mairinque'],
            ['codigo' => 236, 'nome' => 'Etec Gustavo Teixeira'],
            ['codigo' => 237, 'nome' => 'Etec de Santa Rosa de Viterbo'],
            ['codigo' => 238, 'nome' => 'Etec Irmã Agostina (Capela do Socorro)'],
            ['codigo' => 239, 'nome' => 'Etec de Registro'],
            ['codigo' => 240, 'nome' => 'Etec Padre Carlos Leôncio da Silva'],
            ['codigo' => 241, 'nome' => 'Etec de Embu'],
            ['codigo' => 242, 'nome' => 'Etec Dr. Celso Giglio'],
            ['codigo' => 243, 'nome' => 'Etec de Itararé'],
            ['codigo' => 244, 'nome' => 'Etec Cidade do Livro'],
            ['codigo' => 245, 'nome' => 'Etec Antônio Furlan'],
            ['codigo' => 246, 'nome' => 'Etec Dr. Nelson Alves Vianna'],
            ['codigo' => 247, 'nome' => 'Etec Mandaqui (Mandaqui)'],
            ['codigo' => 248, 'nome' => 'Etec de Cerquilho'],
            ['codigo' => 249, 'nome' => 'Etec de Itaquaquecetuba'],
            ['codigo' => 252, 'nome' => 'Etec Prof. Adolpho Arruda Mello '],
            ['codigo' => 253, 'nome' => 'Etec Jornalista Roberto Marinho (Brooklin)'],
            ['codigo' => 254, 'nome' => 'Etec Profª Dra. Doroti Quiomi Kanashiro Toyohara (Pirituba)'],
            ['codigo' => 255, 'nome' => 'Etec Alcides Cestari'],
            ['codigo' => 256, 'nome' => 'Etec Bento Carlos Botelho do Amaral'],
            ['codigo' => 260, 'nome' => 'Etec Santa Ifigênia (Santa Ifigênia)'],
            ['codigo' => 261, 'nome' => 'Etec Darcy Pereira de Moraes'],
            ['codigo' => 262, 'nome' => 'Etec Bartolomeu Bueno da Silva – Anhanguera'],
            ['codigo' => 263, 'nome' => 'Etec de Ibaté'],
            ['codigo' => 264, 'nome' => 'Etec Armando Pannunzio'],
            ['codigo' => 266, 'nome' => 'Etec de Peruíbe'],
            ['codigo' => 267, 'nome' => 'Etec de Esportes – Curt Walter Otto Baumgart (Vila Maria)'],
            ['codigo' => 268, 'nome' => 'Etec Prefeito Braz Paschoalin'],
            ['codigo' => 271, 'nome' => 'Etec de Mairiporã'],
            ['codigo' => 273, 'nome' => 'Etec Sebrae (Campos Elíseos)'],
            ['codigo' => 274, 'nome' => 'Etec Profª Luzia Maria Machado'],
            ['codigo' => 277, 'nome' => 'Etec de Santa Fé do Sul'],
            ['codigo' => 279, 'nome' => 'Etec Paulo do Carmo Monteiro'],
            ['codigo' => 281, 'nome' => 'Etec de Apiaí'],
            ['codigo' => 282, 'nome' => 'Etec Rio Grande da Serra'],
            ['codigo' => 285, 'nome' => 'Etec Itaquera II (Itaquera)'],
            ['codigo' => 287, 'nome' => 'Etec João Elias Margutti'],
            ['codigo' => 289, 'nome' => 'Etec de Porto Feliz'],
            ['codigo' => 293, 'nome' => 'Etec de Taboão da Serra'],
            ['codigo' => 295, 'nome' => 'Etec de Guarulhos'],
            ['codigo' => 300, 'nome' => 'Etec José Miguel Soares'],
            ['codigo' => 302, 'nome' => 'Etec Sumaré Cidade Orquídea'],
            ['codigo' => 303, 'nome' => 'Etec de Cravinhos'],
            ['codigo' => 304, 'nome' => 'Etec de Guaíra'],
            ['codigo' => 306, 'nome' => 'Etec de Bragança Paulista'],
            ['codigo' => 314, 'nome' => 'Etec Vereador Valdivino Antônio Marcusso'],
        ];

        $now = now();

        $rows = array_map(function ($etec) use ($now) {
            return [
                'codigo' => $etec['codigo'],
                'nome' => $etec['nome'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $etecs);

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('etecs')->insert($chunk);
        }
    }
}
